#!/bin/sh

#check if device have internet access
if ! ping -c 1 google.com  >>/dev/null;then
	printf "Please make sure you have internet access.\n" && exit 1
fi

#check if script is running as root
#if [ ! "$(id -u)" -eq 0 ];then
#       printf "Please run this script with root privileges.\n" && exit 1
#fi

#update
#sudo apt update && sudo apt upgrade

#install needed programs
sudo apt install python3-pip python3-django haproxy git

#directories
CORE_DIR="$HOME"/.local/share/capstone
TMP_DIR="$HOME"/capstone-temp

#create temp dir
[ ! -d "$TMP_DIR" ] && mkdir -p "$TMP_DIR"

#CORE_DIR="$HOME"/git/repos/capstone
[ ! -d "$CORE_DIR" ] && mkdir -p "$CORE_DIR"

#clone the repository
cd "$TMP_DIR" && git clone https://gitlab.com/besonia.ma13/capstone

#mv to install
cd "$TMP_DIR" && mv capstone/* "$CORE_DIR"

#move load-balancer script to bin
sudo mv "$CORE_DIR"/script/load-balancer /usr/bin/

#remove temp dir
rm -rf "$TMP_DIR"

#make scripts executable
chmod +x "$CORE_DIR"/script/*

#run haproxy configuration
sh "$CORE_DIR"/script/configure

#start server management module
cd "$CORE_DIR"/django/server_management_module/ && python3 manage.py runserver 0.0.0.0:8000 &

#start Mariadb Database
sudo /opt/lampp/ctlscript.sh start mysql &

printf "\nDONE!"
