#!/bin/sh

CORE_DIR=/usr/share/capstone/

if [ ! "$(id -u)" -eq 0 ];then
	printf "Please run this script with root privileges.\n" && exit 1
fi

help(){ \
	printf "Usage : options\n\n"
	printf "Options:\n"
	printf "\tstart\n"
	printf "\t\tstarts all there is to start( mariadb, haproxy, server management module).\n"
	printf "\tstop\n"
	printf "\t\tstops all running services( mariadb, haproxy, server management module).\n"
	printf "\trestart\n"
	printf "\t\trestarts all running services.\n"
	printf "\tconfigure\n"
	printf "\t\truns the configuration for haproxy.\n"
	printf "\thelp\n"
	printf "\t\tPrints this message.\n"
}

start(){ \
	sudo /opt/lampp/ctrl.sh start mysql &
	sudo haproxy -f "$CORE_DIR"/configuration/haproxy.cfg &
	python3 "$CORE_DIR"/django/server_management_module/manage.py runserver &
}

stop(){ \
	sudo /opt/lampp/ctrl.sh stop mysql &
	sudo killall -q haproxy
	killall -q python3
}

restart(){ \
	stop
	start
}

configure(){ \
	sudo "$CORE_DIR"/script/configure
}

case "$1" in
	help) help;;
	start) start;;
	stop) stop;;
	restart) restart;;
	configure) configure;;
	*) printf "Invalid Option\n"; help
esac
