#!/bin/sh

CORE_DIR="$HOME"/.local/share/capstone

req_sudo(){
if [ ! "$(id -u)" -eq 0 ];then
	printf "Please run this script with root privileges.\n" && exit 1
fi
}

help(){ \
	printf "Usage : options\n\n"
	printf "Options:\n"
	printf "\tstart\n"
	printf "\t\tstarts all there is to start( mariadb, haproxy).\n"
	printf "\tstop\n"
	printf "\t\tstops all running services( mariadb, haproxy).\n"
	printf "\trestart\n"
	printf "\t\trestarts all running services.\n"
	printf "\tconfigure\n"
	printf "\t\truns the configuration for haproxy.\n"
	printf "\tuninstall\n"
	printf "\t\tuninstalls load balancer setup..\n"
	printf "\thelp\n"
	printf "\t\tPrints this message.\n"
}

start(){ \
	req_sudo
	sudo /opt/lampp/ctlscript.sh start mysql &
	sudo haproxy -f "$CORE_DIR"/configuration/haproxy.cfg &
	cd "$HOME"/.local/share/capstone/django/server_management_module/ && python3 manage.py runserver 0.0.0.0:8000
}

stop(){ \
	req_sudo
	sudo /opt/lampp/ctlscript.sh stop mysql &
	sudo killall -q haproxy
	killall -q python3
}

restart(){ \
	stop
	start
}

configure(){ \
	sh "$CORE_DIR"/script/configure
}

uninstall(){ \
	req_sudo
	sh "$CORE_DIR"/script/uninstall
}

case "$1" in
	help) help;;
	start) start;;
	stop) stop;;
	restart) restart;;
	configure) configure;;
	uninstall) uninstall;;
	*) printf "Invalid Option\n"; help
esac
