#!/bin/sh

echo "Warning:"
echo "Before executing this script, please make sure you have an internet connection."
sleep 3
ping google.com -c 1 >>/dev/null || exit 1

#sudo apt update && sudo apt upgrade

#sudo apt install python3-pip python3-django haproxy git

core_dir="$HOME"/capstone2

cd ~/ && git clone https://github.com/besoniama13/IT192
cd ~/ && mv IT192 capstone2

chmod +x "$core_dir"/script/*
sh "$core_dir"/script/configure
